praha-inc/praha-challenge-7

F0yWy8HaLlWoST/01_データベース設計/01_DBモデリング1/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/02_DBモデリング2/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/03_DBモデリング3/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/04_DBモデリング4/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/05_DBモデリング5/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/06_データベース設計のアンチパターンを学ぶ1/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/07_データベース設計のアンチパターンを学ぶ2/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/08_データベース設計のアンチパターンを学ぶ3/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/09_データベース設計のアンチパターンを学ぶ4/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/10_データベース設計のアンチパターンを学ぶ5/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/11_データベース設計のアンチパターンを学ぶ6/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/12_データベース設計のアンチパターンを学ぶ7/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/13_データベース設計のアンチパターンを学ぶ8/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/14_データベース設計のアンチパターンを学ぶ9/kadai_01.md
=> feat: データベース設計のフォルダ作成

I84PdeRyF2ApGF/db_modeling01/task_01/dbModeling_01.pu
[DBモデリング1](https://airtable.com/appEMvY3FsesCpF8G/tbl4FviBLqTJHLjP4/viwvs2HU05ufvqKUD/recaGGRzj3p38rdMX?blocks=hide)の課題1
持ち帰りの注文をした顧客の情報を格納する。
顧客の注文情報を格納する。
支払有無は支払日が入力されているかで判断。
ひとつの注文票に対して、どの商品が、どれだけ注文されているかの情報を格納する。
寿司かセットメニューかの情報と各メニューの値段を格納する。
各寿司の名称を格納する。
各セットメニューの名称に加え、寿司の盛り合わせなどの場合は、セット詳細情報が取得できるようにセット詳細IDを格納する。
セットメニューがどの寿司で構成されているかの情報を確認する。
* メニューをお好み寿司かセットメニューかを分けている部分でテーブルが少し複雑になってしまっているかもしれません。
このようにしている意図としては、セットメニューが寿司の盛り合わせであるものと、鉄火丼のような寿司が関係ないものとが存在しているため、セットメニュー詳細テーブルを作成しております。
* カーディナリティに関してもこれで問題ないか不安です。
=> DBモデリング1_課題1

LNyxHj7XnmM4KR/DB_Modeling/DBモデリング1/課題1/UML.pu
- [DBモデリング1_課題1](https://airtable.com/appEMvY3FsesCpF8G/tbl4FviBLqTJHLjP4/viwvs2HU05ufvqKUD/recaGGRzj3p38rdMX?blocks=hide)
- 持ち帰り以外の注文にも対応できるように、持ち帰りフラグ、税率を管理するようにしました。
- 各テーブルのリレーション、カーディナリティに自信がありません、、、🤔
=> [add]create_shushi_order_ER_diagram

F0yWy8HaLlWoST/01_データベース設計/01_DBモデリング1/.env, F0yWy8HaLlWoST/01_データベース設計/01_DBモデリング1/Dockerfile, F0yWy8HaLlWoST/01_データベース設計/01_DBモデリング1/conf/my.cnf, F0yWy8HaLlWoST/01_データベース設計/01_DBモデリング1/docker-compose.yml, F0yWy8HaLlWoST/01_データベース設計/01_DBモデリング1/kadai_03.md, F0yWy8HaLlWoST/01_データベース設計/01_DBモデリング1/kadai_04.md, F0yWy8HaLlWoST/01_データベース設計/01_DBモデリング1/scripts/initDb.sql
下記対応いたしましたので、ご確認のほどよろしくお願いいたします！
- docker環境の構築
- デモデータの作成
- ユースケースクエリの作成
=> DBモデリング1-4

95IG7y3HHX7yl4/01_データベース(設計と基礎)/11_データベース設計のアンチパターンを学ぶ6/01_DDL.sql, 95IG7y3HHX7yl4/01_データベース(設計と基礎)/11_データベース設計のアンチパターンを学ぶ6/02_ER図.wsd, 95IG7y3HHX7yl4/01_データベース(設計と基礎)/11_データベース設計のアンチパターンを学ぶ6/課題.md
=> データベース設計のアンチパターンを学ぶ6

F0yWy8HaLlWoST/01_データベース設計/03_DBモデリング3/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/03_DBモデリング3/kadai_02.md
DBモデリング3のER図を作成しました！
レビュお願いいたします！（課題2の方だけで問題ないです！）
=> feat: DB3 ER図作成

F0yWy8HaLlWoST/01_データベース設計/03_DBモデリング3/.env, F0yWy8HaLlWoST/01_データベース設計/03_DBモデリング3/Dockerfile, F0yWy8HaLlWoST/01_データベース設計/03_DBモデリング3/conf/my.cnf, F0yWy8HaLlWoST/01_データベース設計/03_DBモデリング3/docker-compose.yml, F0yWy8HaLlWoST/01_データベース設計/03_DBモデリング3/kadai_02.md, F0yWy8HaLlWoST/01_データベース設計/03_DBモデリング3/scripts/initDb.sql
https://github.com/praha-inc/praha-challenge-7/pull/51#issuecomment-1565174375
なぜか削除されたので再作成
=> feat: db modeling 3 DDL

F0yWy8HaLlWoST/01_データベース設計/05_DBモデリング5/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/05_DBモデリング5/kadai_02.md
DBモデリング5のER図作成いたしました！
ご確認のほどよろしくお願いいたします
=> feat: DBモデリング5 ER図作成

F0yWy8HaLlWoST/01_データベース設計/05_DBモデリング5/.env, F0yWy8HaLlWoST/01_データベース設計/05_DBモデリング5/Dockerfile, F0yWy8HaLlWoST/01_データベース設計/05_DBモデリング5/conf/my.cnf, F0yWy8HaLlWoST/01_データベース設計/05_DBモデリング5/docker-compose.yml, F0yWy8HaLlWoST/01_データベース設計/05_DBモデリング5/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/05_DBモデリング5/scripts/initDb.sql
DBモデリング５のDDL/DML/ユースケースクエリ作成いたしました！
ご確認のほどよろしくお願いいたします！
=> feat: db5 ddl/dml/usecase

95IG7y3HHX7yl4/02_テスト/01_jestで単体テストを書こう/01_jest_practice/.gitignore, 95IG7y3HHX7yl4/02_テスト/01_jestで単体テストを書こう/01_jest_practice/babel.config.js, 95IG7y3HHX7yl4/02_テスト/01_jestで単体テストを書こう/01_jest_practice/package-lock.json, 95IG7y3HHX7yl4/02_テスト/01_jestで単体テストを書こう/01_jest_practice/package.json, 95IG7y3HHX7yl4/02_テスト/01_jestで単体テストを書こう/01_jest_practice/sum.js, 95IG7y3HHX7yl4/02_テスト/01_jestで単体テストを書こう/01_jest_practice/sum.test.js, 95IG7y3HHX7yl4/02_テスト/01_jestで単体テストを書こう/課題.md, 95IG7y3HHX7yl4/02_テスト/README.md
課題１は、jestのドキュメントを読む課題なのでレビューは不要です。
課題２のレビューをお願い致します。
レビューの方法としては、フォークした私のレポジトリーをclone頂いてご確認いただくのが良いかなと考えています。
コメントは、このPRでもフォークしたレポジトリに作成した[PR](https://github.com/YamazakiYusuke/praha-challenge-templates/pull/1)でもどちらでも大丈夫です。
お手数ですが、レビューよろしくお願いいたします🙇‍♂
以下テスト実行までの手順
```
// 1. 任意のderectoryにrepositoryをclone
git clone https://github.com/YamazakiYusuke/praha-challenge-templates.git
// 2. 作業directoryに移動
cd praha-challenge-templates/jestSample/
// 3. 作業branchに移動
git switch feature/UnitTestWithJest/01/2B/yamazakiY
// 4. パッケージのインストール
npm install
// 5. テスト実行
npm test
```
=> jestで単体テストを書こう　課題２

F0yWy8HaLlWoST/01_データベース設計/06_データベース設計のアンチパターンを学ぶ1/kadai.md, F0yWy8HaLlWoST/01_データベース設計/06_データベース設計のアンチパターンを学ぶ1/kadai_01.md
データベース設計のアンチパターンを学ぶ1対応いたしましたので、レビュお願い致します！
=> feat: データベース設計のアンチパターンを学ぶ1

F0yWy8HaLlWoST/01_データベース設計/07_データベース設計のアンチパターンを学ぶ2/kadai.md, F0yWy8HaLlWoST/01_データベース設計/07_データベース設計のアンチパターンを学ぶ2/kadai_01.md
データベース設計のアンチパターンを学ぶ2を対応しました！お手すきでレビュお願い致します！
=> feat: データベース設計のアンチパターンを学ぶ2

F0yWy8HaLlWoST/01_データベース設計/08_データベース設計のアンチパターンを学ぶ3/kadai.md, F0yWy8HaLlWoST/01_データベース設計/08_データベース設計のアンチパターンを学ぶ3/kadai_01.md
データベース設計のアンチパターンを学ぶ3対応いたしましたので、ご確認のほどよろしくお願いいたします！
=> feat: データベース設計のアンチパターンを学ぶ3

F0yWy8HaLlWoST/01_データベース設計/04_DBモデリング4/.env, F0yWy8HaLlWoST/01_データベース設計/04_DBモデリング4/Dockerfile, F0yWy8HaLlWoST/01_データベース設計/04_DBモデリング4/conf/my.cnf, F0yWy8HaLlWoST/01_データベース設計/04_DBモデリング4/docker-compose.yml, F0yWy8HaLlWoST/01_データベース設計/04_DBモデリング4/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/04_DBモデリング4/scripts/initDb.sql
DBモデリング４のDDL/DML、ユースケースクエリ作成いたしました！
ご確認のほどよろしくお願いいたします！
=> feat: db4 ddl作成

F0yWy8HaLlWoST/01_データベース設計/09_データベース設計のアンチパターンを学ぶ4/kadai.md, F0yWy8HaLlWoST/01_データベース設計/09_データベース設計のアンチパターンを学ぶ4/kadai_01.md
データベース設計のアンチパターンを学ぶ4対応いたしましたので、ご確認のほどよろしくお願いいたします！
=> feat: データベース設計のアンチパターンを学ぶ4

F0yWy8HaLlWoST/01_データベース設計/10_データベース設計のアンチパターンを学ぶ5/kadai.md, F0yWy8HaLlWoST/01_データベース設計/10_データベース設計のアンチパターンを学ぶ5/kadai_01.md
データベース設計のアンチパターンを学ぶ5完了いたしましたので、レビュお願い致します！
=> feat: データベース設計のアンチパターンを学ぶ5

F0yWy8HaLlWoST/01_データベース設計/11_データベース設計のアンチパターンを学ぶ6/kadai.md, F0yWy8HaLlWoST/01_データベース設計/11_データベース設計のアンチパターンを学ぶ6/kadai_01.md
アンチパターン6対応しました！お手すきでレビュお願いいたします:おじぎ:
=> feat: データベース設計のアンチパターンを学ぶ6

F0yWy8HaLlWoST/01_データベース設計/01_DBモデリング1/kadai_03.md, F0yWy8HaLlWoST/01_データベース設計/02_DBモデリング2/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/03_DBモデリング3/kadai_02.md, F0yWy8HaLlWoST/01_データベース設計/04_DBモデリング4/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/05_DBモデリング5/kadai_01.md, F0yWy8HaLlWoST/01_データベース設計/05_DBモデリング5/kadai_02.md
「アンチパターンを踏まえてDBモデリングを見直そう」を実施しました！
レビュお願い致します！
=> fix: アンチパターンを受けてDBモデリング修正

T3G7x3TAR4lWsg/外部キー制約/課題.md
@YamazakiYusuke @hira-kenta 
お疲れ様です。お手すきの時にレビューお願いします(-m-)
=> 外部キー制約について課題対応

F0yWy8HaLlWoST/01_データベース設計/16_マルチテナントについて/kadai.md
マルチテナントについて対応しましたのでレビュお願い致します！（rich diffにすればテーブル表示になります！）
=> feat: マルチテナントについて

F0yWy8HaLlWoST/01_データベース設計/17_外部キー制約について考える/kadai.md
外部キー制約について考える対応いたしましたので、お手すきでレビュお願い致します！
=> 外部キー制約について考える

95IG7y3HHX7yl4/02_テスト/02_storybookを作ろう/課題.md
課題.mdのご確認よろしくお願いいします🙇‍♂
課題1,2は別repositoryで作業しています。URL先のPRのご確認よろしくお願いいたします。
=> storybookを作ろう

T3G7x3TAR4lWsg/テスト/20.storybookを作ろう/課題.md
@hira-kenta @YamazakiYusuke 
いやぁ、、勉強になりますが骨がありますねぇ。
山崎さんが通った道が、かくも一つ一つ遠いものかと噛み締めます。
=> 課題20.StoryBook実装の課題対応

I84PdeRyF2ApGF/Test/20_storybook/課題.md
storybook課題を行いました！
初めて触りましたが面白いですね…。
使いこなすには時間がかかりそうですが😂
=> storybookを作ろう 課題対応

F0yWy8HaLlWoST/01_データベース設計/18_データベースにおけるNULLの扱い/kadai.md
データベースにおけるNULLの扱い対応しました！レビュお願いします
=> データベースにおけるNULLの扱い

95IG7y3HHX7yl4/02_テスト/04_ビジュアル・リグレッションテストを書こう/課題.md
課題1は導入がうまく行かずに心が折れそうになったのでスキップしました😢
課題2~3のレビューをお願いします。
もしかしたら、ビジュアル・リグレッションテストの導入方法、課題で推奨している[storyshot-puppeteer](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-puppeteer)ではなくて、reg-suit + Storycapとかだとうまくいくかもしれないので、気力が復活したらもう一度トライしてみます。
課題.mdのご確認よろしくお願いいします🙇‍♂
=> ビジュアル・リグレッションテストを書こう

F0yWy8HaLlWoST/02_テスト/01_jestで単体テストを書こう/kadai_01.md
jestで単体テストを書こうやっと終わりました！レビュお願いします！
=> feat: jestで単体テストを書こう

F0yWy8HaLlWoST/02_テスト/02_storybookを作ろう/kadai_01.md
storybookを作ろう課題完了いたしましたので、ご確認のほどよろしくお願いいたします！
=> feat: storybookを作ろう

F0yWy8HaLlWoST/02_テスト/04_ビジュアル・リグレッションテストを書こう/kadai_01.md
ビジュアル・リグレッションテストを書こう課題完了いたしましたので、レビュお願い致します！
=> feat: ビジュアル・リグレッションテストを書こう

95IG7y3HHX7yl4/05_フロントエンド/01_はじめに React ( Next.js ) の環境を立ち上げよう/課題.md
Next.js をセットアップして、起動するだけの課題なのでレビューは不要です。
=> 37. はじめに React ( Next.js ) の環境を立ち上げよう
